# Generated by Django 5.2.17 on 2026-08-12 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_lsaprofile_skill_bookingrequest_booking_payment_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['lsa', 'start_time', 'end_time'], name='booking_lsa_time_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status'], name='booking_status_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingrequest',
            index=models.Index(fields=['preferred_lsa', 'start_time', 'end_time'], name='booking_req_lsa_time_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingrequest',
            index=models.Index(fields=['status'], name='booking_req_status_idx'),
        ),
    ]
