# Generated by Django 5.2.17 on 2026-08-12 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_booking_lsa_time_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='booking',
            name='booking_lsa_time_idx',
        ),
        migrations.RemoveIndex(
            model_name='booking',
            name='booking_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='bookingrequest',
            name='booking_req_lsa_time_idx',
        ),
        migrations.RemoveIndex(
            model_name='bookingrequest',
            name='booking_req_status_idx',
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='booking', to='bookings.bookingrequest'),
        ),
    ]
